#define blockWidth 60.f
#define blockHeight 20.f
#define bonusBallRadius 10.f
#define ballVelocity 6.f
#define windowWidth 800
#define windowHeight 600
#define paddleHeight 20.f
#define paddleVelocity 9.f
#define bonusVelocity 3.f
#define bulletVelocity 9.f
#define bulletRadius 5.f
